//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imageLinksWebService_Test.imagelinks {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", ConfigurationName="imagelinks.ImageLinks")]
    public interface ImageLinks {
        
        // CODEGEN: Generating message contract since message ProcessNodesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataObject))]
        imageLinksWebService_Test.imagelinks.ProcessNodesResponse ProcessNodes(imageLinksWebService_Test.imagelinks.ProcessNodesRequest request);
        
        // CODEGEN: Generating message contract since message ProcessNodesWithUploadRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataObject))]
        imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadResponse ProcessNodesWithUpload(imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadRequest request);
        
        // CODEGEN: Generating message contract since message GetNodeExtendedDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataObject))]
        imageLinksWebService_Test.imagelinks.GetNodeExtendedDataResponse GetNodeExtendedData(imageLinksWebService_Test.imagelinks.GetNodeExtendedDataRequest request);
        
        // CODEGEN: Generating message contract since message ResizeOriginalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(serviceDataObject))]
        imageLinksWebService_Test.imagelinks.ResizeOriginalResponse ResizeOriginal(imageLinksWebService_Test.imagelinks.ResizeOriginalRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.ecm.opentext.com")]
    public partial class OTAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authenticationTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
                this.RaisePropertyChanged("AuthenticationToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResizeOriginalResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessNodesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Size))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessNodesParams))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Version))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeVersionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeReservationInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeReferenceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodePermissions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimitiveValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Metadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeFeature))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NodeContainerInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Node))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayValues))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageLinksNodeData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public abstract partial class serviceDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class ResizeOriginalResult : serviceDataObject {
        
        private string originalContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OriginalContext {
            get {
                return this.originalContextField;
            }
            set {
                this.originalContextField = value;
                this.RaisePropertyChanged("OriginalContext");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class ProcessNodesResult : serviceDataObject {
        
        private string previewContextField;
        
        private int previewIdField;
        
        private string splashContextField;
        
        private System.Nullable<int> splashIdField;
        
        private bool splashIdFieldSpecified;
        
        private string thumbnailContextField;
        
        private int thumbnailIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PreviewContext {
            get {
                return this.previewContextField;
            }
            set {
                this.previewContextField = value;
                this.RaisePropertyChanged("PreviewContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PreviewId {
            get {
                return this.previewIdField;
            }
            set {
                this.previewIdField = value;
                this.RaisePropertyChanged("PreviewId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SplashContext {
            get {
                return this.splashContextField;
            }
            set {
                this.splashContextField = value;
                this.RaisePropertyChanged("SplashContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> SplashId {
            get {
                return this.splashIdField;
            }
            set {
                this.splashIdField = value;
                this.RaisePropertyChanged("SplashId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SplashIdSpecified {
            get {
                return this.splashIdFieldSpecified;
            }
            set {
                this.splashIdFieldSpecified = value;
                this.RaisePropertyChanged("SplashIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ThumbnailContext {
            get {
                return this.thumbnailContextField;
            }
            set {
                this.thumbnailContextField = value;
                this.RaisePropertyChanged("ThumbnailContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ThumbnailId {
            get {
                return this.thumbnailIdField;
            }
            set {
                this.thumbnailIdField = value;
                this.RaisePropertyChanged("ThumbnailId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class Size : serviceDataObject {
        
        private int heightField;
        
        private int widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class ProcessNodesParams : serviceDataObject {
        
        private string convertedByField;
        
        private ArrayValues[] eXIFField;
        
        private ArrayValues[] gPSField;
        
        private ArrayValues[] iCCField;
        
        private ArrayValues[] iNFOField;
        
        private ArrayValues[] iPTCField;
        
        private int originalNodeIdField;
        
        private Size originalSizeField;
        
        private Size previewSizeField;
        
        private Size splashSizeField;
        
        private Size thumbSizeField;
        
        private string warningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ConvertedBy {
            get {
                return this.convertedByField;
            }
            set {
                this.convertedByField = value;
                this.RaisePropertyChanged("ConvertedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXIF", Order=1)]
        public ArrayValues[] EXIF {
            get {
                return this.eXIFField;
            }
            set {
                this.eXIFField = value;
                this.RaisePropertyChanged("EXIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GPS", Order=2)]
        public ArrayValues[] GPS {
            get {
                return this.gPSField;
            }
            set {
                this.gPSField = value;
                this.RaisePropertyChanged("GPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ICC", Order=3)]
        public ArrayValues[] ICC {
            get {
                return this.iCCField;
            }
            set {
                this.iCCField = value;
                this.RaisePropertyChanged("ICC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INFO", Order=4)]
        public ArrayValues[] INFO {
            get {
                return this.iNFOField;
            }
            set {
                this.iNFOField = value;
                this.RaisePropertyChanged("INFO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IPTC", Order=5)]
        public ArrayValues[] IPTC {
            get {
                return this.iPTCField;
            }
            set {
                this.iPTCField = value;
                this.RaisePropertyChanged("IPTC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int OriginalNodeId {
            get {
                return this.originalNodeIdField;
            }
            set {
                this.originalNodeIdField = value;
                this.RaisePropertyChanged("OriginalNodeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Size OriginalSize {
            get {
                return this.originalSizeField;
            }
            set {
                this.originalSizeField = value;
                this.RaisePropertyChanged("OriginalSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Size PreviewSize {
            get {
                return this.previewSizeField;
            }
            set {
                this.previewSizeField = value;
                this.RaisePropertyChanged("PreviewSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public Size SplashSize {
            get {
                return this.splashSizeField;
            }
            set {
                this.splashSizeField = value;
                this.RaisePropertyChanged("SplashSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Size ThumbSize {
            get {
                return this.thumbSizeField;
            }
            set {
                this.thumbSizeField = value;
                this.RaisePropertyChanged("ThumbSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
                this.RaisePropertyChanged("Warning");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class ArrayValues : serviceDataObject {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Version : serviceDataObject {
        
        private string commentField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private bool createDateFieldSpecified;
        
        private System.Nullable<System.DateTime> fileCreateDateField;
        
        private bool fileCreateDateFieldSpecified;
        
        private string fileCreatorField;
        
        private long fileDataSizeField;
        
        private System.Nullable<System.DateTime> fileModifyDateField;
        
        private bool fileModifyDateFieldSpecified;
        
        private string filenameField;
        
        private int filePlatformField;
        
        private int fileResSizeField;
        
        private string fileTypeField;
        
        private int idField;
        
        private int lockedField;
        
        private System.Nullable<int> lockedByField;
        
        private bool lockedByFieldSpecified;
        
        private System.Nullable<System.DateTime> lockedDateField;
        
        private bool lockedDateFieldSpecified;
        
        private Metadata metadataField;
        
        private string mimeTypeField;
        
        private System.Nullable<System.DateTime> modifyDateField;
        
        private bool modifyDateFieldSpecified;
        
        private string nameField;
        
        private int nodeIDField;
        
        private int numberField;
        
        private int ownerField;
        
        private int providerIDField;
        
        private string providerNameField;
        
        private string typeField;
        
        private int verMajorField;
        
        private int verMinorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("CreateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> FileCreateDate {
            get {
                return this.fileCreateDateField;
            }
            set {
                this.fileCreateDateField = value;
                this.RaisePropertyChanged("FileCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileCreateDateSpecified {
            get {
                return this.fileCreateDateFieldSpecified;
            }
            set {
                this.fileCreateDateFieldSpecified = value;
                this.RaisePropertyChanged("FileCreateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileCreator {
            get {
                return this.fileCreatorField;
            }
            set {
                this.fileCreatorField = value;
                this.RaisePropertyChanged("FileCreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long FileDataSize {
            get {
                return this.fileDataSizeField;
            }
            set {
                this.fileDataSizeField = value;
                this.RaisePropertyChanged("FileDataSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FileModifyDate {
            get {
                return this.fileModifyDateField;
            }
            set {
                this.fileModifyDateField = value;
                this.RaisePropertyChanged("FileModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileModifyDateSpecified {
            get {
                return this.fileModifyDateFieldSpecified;
            }
            set {
                this.fileModifyDateFieldSpecified = value;
                this.RaisePropertyChanged("FileModifyDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("Filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int FilePlatform {
            get {
                return this.filePlatformField;
            }
            set {
                this.filePlatformField = value;
                this.RaisePropertyChanged("FilePlatform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int FileResSize {
            get {
                return this.fileResSizeField;
            }
            set {
                this.fileResSizeField = value;
                this.RaisePropertyChanged("FileResSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
                this.RaisePropertyChanged("Locked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> LockedBy {
            get {
                return this.lockedByField;
            }
            set {
                this.lockedByField = value;
                this.RaisePropertyChanged("LockedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockedBySpecified {
            get {
                return this.lockedByFieldSpecified;
            }
            set {
                this.lockedByFieldSpecified = value;
                this.RaisePropertyChanged("LockedBySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LockedDate {
            get {
                return this.lockedDateField;
            }
            set {
                this.lockedDateField = value;
                this.RaisePropertyChanged("LockedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LockedDateSpecified {
            get {
                return this.lockedDateFieldSpecified;
            }
            set {
                this.lockedDateFieldSpecified = value;
                this.RaisePropertyChanged("LockedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Metadata Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
                this.RaisePropertyChanged("ModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifyDateSpecified {
            get {
                return this.modifyDateFieldSpecified;
            }
            set {
                this.modifyDateFieldSpecified = value;
                this.RaisePropertyChanged("ModifyDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int NodeID {
            get {
                return this.nodeIDField;
            }
            set {
                this.nodeIDField = value;
                this.RaisePropertyChanged("NodeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("ProviderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int VerMajor {
            get {
                return this.verMajorField;
            }
            set {
                this.verMajorField = value;
                this.RaisePropertyChanged("VerMajor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int VerMinor {
            get {
                return this.verMinorField;
            }
            set {
                this.verMinorField = value;
                this.RaisePropertyChanged("VerMinor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Metadata : serviceDataObject {
        
        private AttributeGroup[] attributeGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeGroups", Order=0)]
        public AttributeGroup[] AttributeGroups {
            get {
                return this.attributeGroupsField;
            }
            set {
                this.attributeGroupsField = value;
                this.RaisePropertyChanged("AttributeGroups");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class AttributeGroup : serviceDataObject {
        
        private string displayNameField;
        
        private string keyField;
        
        private string typeField;
        
        private DataValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=3)]
        public DataValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TableValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrimitiveValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class DataValue : serviceDataObject {
        
        private string descriptionField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class TableValue : DataValue {
        
        private RowValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public RowValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class RowValue : DataValue {
        
        private DataValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public DataValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class PrimitiveValue : DataValue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class StringValue : PrimitiveValue {
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", Order=0)]
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class RealValue : PrimitiveValue {
        
        private System.Nullable<double>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<double>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class IntegerValue : PrimitiveValue {
        
        private System.Nullable<int>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<int>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class DateValue : PrimitiveValue {
        
        private System.Nullable<System.DateTime>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Core.service.livelink.opentext.com")]
    public partial class BooleanValue : PrimitiveValue {
        
        private System.Nullable<bool>[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Values", IsNullable=true, Order=0)]
        public System.Nullable<bool>[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeVersionInfo : serviceDataObject {
        
        private bool advancedVersionControlField;
        
        private System.Nullable<long> fileDataSizeField;
        
        private bool fileDataSizeFieldSpecified;
        
        private System.Nullable<int> fileResSizeField;
        
        private bool fileResSizeFieldSpecified;
        
        private System.Nullable<int> majorField;
        
        private bool majorFieldSpecified;
        
        private string mimeTypeField;
        
        private bool supportsAdvancedVersionControlField;
        
        private int versionNumField;
        
        private Version[] versionsField;
        
        private System.Nullable<int> versionsToKeepField;
        
        private bool versionsToKeepFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AdvancedVersionControl {
            get {
                return this.advancedVersionControlField;
            }
            set {
                this.advancedVersionControlField = value;
                this.RaisePropertyChanged("AdvancedVersionControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> FileDataSize {
            get {
                return this.fileDataSizeField;
            }
            set {
                this.fileDataSizeField = value;
                this.RaisePropertyChanged("FileDataSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileDataSizeSpecified {
            get {
                return this.fileDataSizeFieldSpecified;
            }
            set {
                this.fileDataSizeFieldSpecified = value;
                this.RaisePropertyChanged("FileDataSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> FileResSize {
            get {
                return this.fileResSizeField;
            }
            set {
                this.fileResSizeField = value;
                this.RaisePropertyChanged("FileResSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileResSizeSpecified {
            get {
                return this.fileResSizeFieldSpecified;
            }
            set {
                this.fileResSizeFieldSpecified = value;
                this.RaisePropertyChanged("FileResSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MajorSpecified {
            get {
                return this.majorFieldSpecified;
            }
            set {
                this.majorFieldSpecified = value;
                this.RaisePropertyChanged("MajorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool SupportsAdvancedVersionControl {
            get {
                return this.supportsAdvancedVersionControlField;
            }
            set {
                this.supportsAdvancedVersionControlField = value;
                this.RaisePropertyChanged("SupportsAdvancedVersionControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int VersionNum {
            get {
                return this.versionNumField;
            }
            set {
                this.versionNumField = value;
                this.RaisePropertyChanged("VersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Versions", Order=7)]
        public Version[] Versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
                this.RaisePropertyChanged("Versions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> VersionsToKeep {
            get {
                return this.versionsToKeepField;
            }
            set {
                this.versionsToKeepField = value;
                this.RaisePropertyChanged("VersionsToKeep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionsToKeepSpecified {
            get {
                return this.versionsToKeepFieldSpecified;
            }
            set {
                this.versionsToKeepFieldSpecified = value;
                this.RaisePropertyChanged("VersionsToKeepSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeReservationInfo : serviceDataObject {
        
        private bool reservedField;
        
        private int reservedByField;
        
        private System.Nullable<System.DateTime> reservedDateField;
        
        private bool reservedDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Reserved {
            get {
                return this.reservedField;
            }
            set {
                this.reservedField = value;
                this.RaisePropertyChanged("Reserved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReservedBy {
            get {
                return this.reservedByField;
            }
            set {
                this.reservedByField = value;
                this.RaisePropertyChanged("ReservedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ReservedDate {
            get {
                return this.reservedDateField;
            }
            set {
                this.reservedDateField = value;
                this.RaisePropertyChanged("ReservedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservedDateSpecified {
            get {
                return this.reservedDateFieldSpecified;
            }
            set {
                this.reservedDateFieldSpecified = value;
                this.RaisePropertyChanged("ReservedDateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeReferenceInfo : serviceDataObject {
        
        private int originalIDField;
        
        private string originalTypeField;
        
        private System.Nullable<int> versionNumField;
        
        private bool versionNumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OriginalID {
            get {
                return this.originalIDField;
            }
            set {
                this.originalIDField = value;
                this.RaisePropertyChanged("OriginalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OriginalType {
            get {
                return this.originalTypeField;
            }
            set {
                this.originalTypeField = value;
                this.RaisePropertyChanged("OriginalType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> VersionNum {
            get {
                return this.versionNumField;
            }
            set {
                this.versionNumField = value;
                this.RaisePropertyChanged("VersionNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionNumSpecified {
            get {
                return this.versionNumFieldSpecified;
            }
            set {
                this.versionNumFieldSpecified = value;
                this.RaisePropertyChanged("VersionNumSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodePermissions : serviceDataObject {
        
        private bool addItemsPermissionField;
        
        private bool deletePermissionField;
        
        private bool deleteVersionsPermissionField;
        
        private bool editAttributesPermissionField;
        
        private bool editPermissionsPermissionField;
        
        private bool modifyPermissionField;
        
        private bool reservePermissionField;
        
        private bool seeContentsPermissionField;
        
        private bool seePermissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AddItemsPermission {
            get {
                return this.addItemsPermissionField;
            }
            set {
                this.addItemsPermissionField = value;
                this.RaisePropertyChanged("AddItemsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool DeletePermission {
            get {
                return this.deletePermissionField;
            }
            set {
                this.deletePermissionField = value;
                this.RaisePropertyChanged("DeletePermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool DeleteVersionsPermission {
            get {
                return this.deleteVersionsPermissionField;
            }
            set {
                this.deleteVersionsPermissionField = value;
                this.RaisePropertyChanged("DeleteVersionsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool EditAttributesPermission {
            get {
                return this.editAttributesPermissionField;
            }
            set {
                this.editAttributesPermissionField = value;
                this.RaisePropertyChanged("EditAttributesPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool EditPermissionsPermission {
            get {
                return this.editPermissionsPermissionField;
            }
            set {
                this.editPermissionsPermissionField = value;
                this.RaisePropertyChanged("EditPermissionsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ModifyPermission {
            get {
                return this.modifyPermissionField;
            }
            set {
                this.modifyPermissionField = value;
                this.RaisePropertyChanged("ModifyPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool ReservePermission {
            get {
                return this.reservePermissionField;
            }
            set {
                this.reservePermissionField = value;
                this.RaisePropertyChanged("ReservePermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool SeeContentsPermission {
            get {
                return this.seeContentsPermissionField;
            }
            set {
                this.seeContentsPermissionField = value;
                this.RaisePropertyChanged("SeeContentsPermission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SeePermission {
            get {
                return this.seePermissionField;
            }
            set {
                this.seePermissionField = value;
                this.RaisePropertyChanged("SeePermission");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeFeature : serviceDataObject {
        
        private System.Nullable<bool> booleanValueField;
        
        private bool booleanValueFieldSpecified;
        
        private System.Nullable<System.DateTime> dateValueField;
        
        private bool dateValueFieldSpecified;
        
        private System.Nullable<int> integerValueField;
        
        private bool integerValueFieldSpecified;
        
        private System.Nullable<long> longValueField;
        
        private bool longValueFieldSpecified;
        
        private string nameField;
        
        private string stringValueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> BooleanValue {
            get {
                return this.booleanValueField;
            }
            set {
                this.booleanValueField = value;
                this.RaisePropertyChanged("BooleanValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BooleanValueSpecified {
            get {
                return this.booleanValueFieldSpecified;
            }
            set {
                this.booleanValueFieldSpecified = value;
                this.RaisePropertyChanged("BooleanValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> DateValue {
            get {
                return this.dateValueField;
            }
            set {
                this.dateValueField = value;
                this.RaisePropertyChanged("DateValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateValueSpecified {
            get {
                return this.dateValueFieldSpecified;
            }
            set {
                this.dateValueFieldSpecified = value;
                this.RaisePropertyChanged("DateValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> IntegerValue {
            get {
                return this.integerValueField;
            }
            set {
                this.integerValueField = value;
                this.RaisePropertyChanged("IntegerValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntegerValueSpecified {
            get {
                return this.integerValueFieldSpecified;
            }
            set {
                this.integerValueFieldSpecified = value;
                this.RaisePropertyChanged("IntegerValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<long> LongValue {
            get {
                return this.longValueField;
            }
            set {
                this.longValueField = value;
                this.RaisePropertyChanged("LongValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongValueSpecified {
            get {
                return this.longValueFieldSpecified;
            }
            set {
                this.longValueFieldSpecified = value;
                this.RaisePropertyChanged("LongValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
                this.RaisePropertyChanged("StringValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class NodeContainerInfo : serviceDataObject {
        
        private int childCountField;
        
        private string[] childTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChildCount {
            get {
                return this.childCountField;
            }
            set {
                this.childCountField = value;
                this.RaisePropertyChanged("ChildCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildTypes", Order=1)]
        public string[] ChildTypes {
            get {
                return this.childTypesField;
            }
            set {
                this.childTypesField = value;
                this.RaisePropertyChanged("ChildTypes");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DocMan.service.livelink.opentext.com")]
    public partial class Node : serviceDataObject {
        
        private System.Nullable<int> catalogField;
        
        private bool catalogFieldSpecified;
        
        private string commentField;
        
        private NodeContainerInfo containerInfoField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private bool createDateFieldSpecified;
        
        private System.Nullable<int> createdByField;
        
        private bool createdByFieldSpecified;
        
        private string displayTypeField;
        
        private NodeFeature[] featuresField;
        
        private int idField;
        
        private bool isContainerField;
        
        private bool isReferenceField;
        
        private bool isReservableField;
        
        private bool isVersionableField;
        
        private Metadata metadataField;
        
        private System.Nullable<System.DateTime> modifyDateField;
        
        private bool modifyDateFieldSpecified;
        
        private string nameField;
        
        private string nicknameField;
        
        private int parentIDField;
        
        private bool partialDataField;
        
        private NodePermissions permissionsField;
        
        private System.Nullable<int> positionField;
        
        private bool positionFieldSpecified;
        
        private NodeReferenceInfo referenceInfoField;
        
        private bool releasedField;
        
        private NodeReservationInfo reservationInfoField;
        
        private string typeField;
        
        private NodeVersionInfo versionInfoField;
        
        private int volumeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> Catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
                this.RaisePropertyChanged("Catalog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CatalogSpecified {
            get {
                return this.catalogFieldSpecified;
            }
            set {
                this.catalogFieldSpecified = value;
                this.RaisePropertyChanged("CatalogSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NodeContainerInfo ContainerInfo {
            get {
                return this.containerInfoField;
            }
            set {
                this.containerInfoField = value;
                this.RaisePropertyChanged("ContainerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("CreateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedBySpecified {
            get {
                return this.createdByFieldSpecified;
            }
            set {
                this.createdByFieldSpecified = value;
                this.RaisePropertyChanged("CreatedBySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DisplayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
                this.RaisePropertyChanged("DisplayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Features", Order=6)]
        public NodeFeature[] Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
                this.RaisePropertyChanged("Features");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsContainer {
            get {
                return this.isContainerField;
            }
            set {
                this.isContainerField = value;
                this.RaisePropertyChanged("IsContainer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsReference {
            get {
                return this.isReferenceField;
            }
            set {
                this.isReferenceField = value;
                this.RaisePropertyChanged("IsReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsReservable {
            get {
                return this.isReservableField;
            }
            set {
                this.isReservableField = value;
                this.RaisePropertyChanged("IsReservable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsVersionable {
            get {
                return this.isVersionableField;
            }
            set {
                this.isVersionableField = value;
                this.RaisePropertyChanged("IsVersionable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Metadata Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> ModifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
                this.RaisePropertyChanged("ModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifyDateSpecified {
            get {
                return this.modifyDateFieldSpecified;
            }
            set {
                this.modifyDateFieldSpecified = value;
                this.RaisePropertyChanged("ModifyDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("Nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
                this.RaisePropertyChanged("ParentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool PartialData {
            get {
                return this.partialDataField;
            }
            set {
                this.partialDataField = value;
                this.RaisePropertyChanged("PartialData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public NodePermissions Permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
                this.RaisePropertyChanged("Permissions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PositionSpecified {
            get {
                return this.positionFieldSpecified;
            }
            set {
                this.positionFieldSpecified = value;
                this.RaisePropertyChanged("PositionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public NodeReferenceInfo ReferenceInfo {
            get {
                return this.referenceInfoField;
            }
            set {
                this.referenceInfoField = value;
                this.RaisePropertyChanged("ReferenceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Released {
            get {
                return this.releasedField;
            }
            set {
                this.releasedField = value;
                this.RaisePropertyChanged("Released");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public NodeReservationInfo ReservationInfo {
            get {
                return this.reservationInfoField;
            }
            set {
                this.reservationInfoField = value;
                this.RaisePropertyChanged("ReservationInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public NodeVersionInfo VersionInfo {
            get {
                return this.versionInfoField;
            }
            set {
                this.versionInfoField = value;
                this.RaisePropertyChanged("VersionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int VolumeID {
            get {
                return this.volumeIDField;
            }
            set {
                this.volumeIDField = value;
                this.RaisePropertyChanged("VolumeID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com")]
    public partial class ImageLinksNodeData : serviceDataObject {
        
        private ArrayValues[] eXIFField;
        
        private ArrayValues[] gPSField;
        
        private ArrayValues[] iCCField;
        
        private ArrayValues[] iPTCField;
        
        private Node nodeField;
        
        private ArrayValues[] nodeExtendedDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EXIF", Order=0)]
        public ArrayValues[] EXIF {
            get {
                return this.eXIFField;
            }
            set {
                this.eXIFField = value;
                this.RaisePropertyChanged("EXIF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GPS", Order=1)]
        public ArrayValues[] GPS {
            get {
                return this.gPSField;
            }
            set {
                this.gPSField = value;
                this.RaisePropertyChanged("GPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ICC", Order=2)]
        public ArrayValues[] ICC {
            get {
                return this.iCCField;
            }
            set {
                this.iCCField = value;
                this.RaisePropertyChanged("ICC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IPTC", Order=3)]
        public ArrayValues[] IPTC {
            get {
                return this.iPTCField;
            }
            set {
                this.iPTCField = value;
                this.RaisePropertyChanged("IPTC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Node Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
                this.RaisePropertyChanged("Node");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NodeExtendedData", Order=5)]
        public ArrayValues[] NodeExtendedData {
            get {
                return this.nodeExtendedDataField;
            }
            set {
                this.nodeExtendedDataField = value;
                this.RaisePropertyChanged("NodeExtendedData");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessNodes", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ProcessNodesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams;
        
        public ProcessNodesRequest() {
        }
        
        public ProcessNodesRequest(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams) {
            this.OTAuthentication = OTAuthentication;
            this.inParams = inParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessNodesResponse", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ProcessNodesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodesResult;
        
        public ProcessNodesResponse() {
        }
        
        public ProcessNodesResponse(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodesResult) {
            this.OTAuthentication = OTAuthentication;
            this.ProcessNodesResult = ProcessNodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessNodesWithUpload", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ProcessNodesWithUploadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=1)]
        public imageLinksWebService_Test.imagelinks.Metadata previewMetadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=2)]
        public imageLinksWebService_Test.imagelinks.Metadata thumbnailMetadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=3)]
        public imageLinksWebService_Test.imagelinks.Metadata splashMetadata;
        
        public ProcessNodesWithUploadRequest() {
        }
        
        public ProcessNodesWithUploadRequest(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams, imageLinksWebService_Test.imagelinks.Metadata previewMetadata, imageLinksWebService_Test.imagelinks.Metadata thumbnailMetadata, imageLinksWebService_Test.imagelinks.Metadata splashMetadata) {
            this.OTAuthentication = OTAuthentication;
            this.inParams = inParams;
            this.previewMetadata = previewMetadata;
            this.thumbnailMetadata = thumbnailMetadata;
            this.splashMetadata = splashMetadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessNodesWithUploadResponse", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ProcessNodesWithUploadResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodesWithUploadResult;
        
        public ProcessNodesWithUploadResponse() {
        }
        
        public ProcessNodesWithUploadResponse(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodesWithUploadResult) {
            this.OTAuthentication = OTAuthentication;
            this.ProcessNodesWithUploadResult = ProcessNodesWithUploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNodeExtendedData", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetNodeExtendedDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public int nodeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=1)]
        public int versionNum;
        
        public GetNodeExtendedDataRequest() {
        }
        
        public GetNodeExtendedDataRequest(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, int nodeId, int versionNum) {
            this.OTAuthentication = OTAuthentication;
            this.nodeId = nodeId;
            this.versionNum = versionNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNodeExtendedDataResponse", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class GetNodeExtendedDataResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ImageLinksNodeData GetNodeExtendedDataResult;
        
        public GetNodeExtendedDataResponse() {
        }
        
        public GetNodeExtendedDataResponse(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ImageLinksNodeData GetNodeExtendedDataResult) {
            this.OTAuthentication = OTAuthentication;
            this.GetNodeExtendedDataResult = GetNodeExtendedDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResizeOriginal", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ResizeOriginalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public int nodeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=1)]
        public imageLinksWebService_Test.imagelinks.Metadata originalMetadata;
        
        public ResizeOriginalRequest() {
        }
        
        public ResizeOriginalRequest(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, int nodeId, imageLinksWebService_Test.imagelinks.Metadata originalMetadata) {
            this.OTAuthentication = OTAuthentication;
            this.nodeId = nodeId;
            this.originalMetadata = originalMetadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResizeOriginalResponse", WrapperNamespace="urn:ImageLinks.service.livelink.opentext.com", IsWrapped=true)]
    public partial class ResizeOriginalResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:api.ecm.opentext.com")]
        public imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ImageLinks.service.livelink.opentext.com", Order=0)]
        public imageLinksWebService_Test.imagelinks.ResizeOriginalResult ResizeOriginalResult;
        
        public ResizeOriginalResponse() {
        }
        
        public ResizeOriginalResponse(imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ResizeOriginalResult ResizeOriginalResult) {
            this.OTAuthentication = OTAuthentication;
            this.ResizeOriginalResult = ResizeOriginalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageLinksChannel : imageLinksWebService_Test.imagelinks.ImageLinks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageLinksClient : System.ServiceModel.ClientBase<imageLinksWebService_Test.imagelinks.ImageLinks>, imageLinksWebService_Test.imagelinks.ImageLinks {
        
        public ImageLinksClient() {
        }
        
        public ImageLinksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageLinksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageLinksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageLinksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imageLinksWebService_Test.imagelinks.ProcessNodesResponse imageLinksWebService_Test.imagelinks.ImageLinks.ProcessNodes(imageLinksWebService_Test.imagelinks.ProcessNodesRequest request) {
            return base.Channel.ProcessNodes(request);
        }
        
        public imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodes(ref imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams) {
            imageLinksWebService_Test.imagelinks.ProcessNodesRequest inValue = new imageLinksWebService_Test.imagelinks.ProcessNodesRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.inParams = inParams;
            imageLinksWebService_Test.imagelinks.ProcessNodesResponse retVal = ((imageLinksWebService_Test.imagelinks.ImageLinks)(this)).ProcessNodes(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.ProcessNodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadResponse imageLinksWebService_Test.imagelinks.ImageLinks.ProcessNodesWithUpload(imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadRequest request) {
            return base.Channel.ProcessNodesWithUpload(request);
        }
        
        public imageLinksWebService_Test.imagelinks.ProcessNodesResult ProcessNodesWithUpload(ref imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, imageLinksWebService_Test.imagelinks.ProcessNodesParams inParams, imageLinksWebService_Test.imagelinks.Metadata previewMetadata, imageLinksWebService_Test.imagelinks.Metadata thumbnailMetadata, imageLinksWebService_Test.imagelinks.Metadata splashMetadata) {
            imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadRequest inValue = new imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.inParams = inParams;
            inValue.previewMetadata = previewMetadata;
            inValue.thumbnailMetadata = thumbnailMetadata;
            inValue.splashMetadata = splashMetadata;
            imageLinksWebService_Test.imagelinks.ProcessNodesWithUploadResponse retVal = ((imageLinksWebService_Test.imagelinks.ImageLinks)(this)).ProcessNodesWithUpload(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.ProcessNodesWithUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imageLinksWebService_Test.imagelinks.GetNodeExtendedDataResponse imageLinksWebService_Test.imagelinks.ImageLinks.GetNodeExtendedData(imageLinksWebService_Test.imagelinks.GetNodeExtendedDataRequest request) {
            return base.Channel.GetNodeExtendedData(request);
        }
        
        public imageLinksWebService_Test.imagelinks.ImageLinksNodeData GetNodeExtendedData(ref imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, int nodeId, int versionNum) {
            imageLinksWebService_Test.imagelinks.GetNodeExtendedDataRequest inValue = new imageLinksWebService_Test.imagelinks.GetNodeExtendedDataRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.nodeId = nodeId;
            inValue.versionNum = versionNum;
            imageLinksWebService_Test.imagelinks.GetNodeExtendedDataResponse retVal = ((imageLinksWebService_Test.imagelinks.ImageLinks)(this)).GetNodeExtendedData(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.GetNodeExtendedDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        imageLinksWebService_Test.imagelinks.ResizeOriginalResponse imageLinksWebService_Test.imagelinks.ImageLinks.ResizeOriginal(imageLinksWebService_Test.imagelinks.ResizeOriginalRequest request) {
            return base.Channel.ResizeOriginal(request);
        }
        
        public imageLinksWebService_Test.imagelinks.ResizeOriginalResult ResizeOriginal(ref imageLinksWebService_Test.imagelinks.OTAuthentication OTAuthentication, int nodeId, imageLinksWebService_Test.imagelinks.Metadata originalMetadata) {
            imageLinksWebService_Test.imagelinks.ResizeOriginalRequest inValue = new imageLinksWebService_Test.imagelinks.ResizeOriginalRequest();
            inValue.OTAuthentication = OTAuthentication;
            inValue.nodeId = nodeId;
            inValue.originalMetadata = originalMetadata;
            imageLinksWebService_Test.imagelinks.ResizeOriginalResponse retVal = ((imageLinksWebService_Test.imagelinks.ImageLinks)(this)).ResizeOriginal(inValue);
            OTAuthentication = retVal.OTAuthentication;
            return retVal.ResizeOriginalResult;
        }
    }
}
